--- 
- name: Wait for the pods to come up with status 'Running'
  hosts: 'all'
  tasks:
    - name: check pod
      command: varname="kubectl wait --for=condition=ready pod -l app=podname --timeout=2s -n dev"
      register: podtest
    - name: check condition
      command: "export podStatus=not"
      when: $varname == error*

    - debug: msg="{{ podtest.stdout }}"